using UnityEngine;
using DroneSwampPathfiner.Core.Environment;
//using DroneSwampPathfiner.Unity;

namespace DroneSwampPathfiner.Unity.Environment
{
    [ExecuteAlways]
    public class ObstacleView : MonoBehaviour
    {
        [Tooltip("Unique ID of the obstacle separate from the drone IDs, autogenerated")]
        public int obstacleID;
        public BoxObstacle Model { get; private set; }

        private void Awake()
        {
            if (obstacleID == 0) obstacleID = GetInstanceID();

            // TODO: Create core model through UI (for now "hardcoded" into the scene)
            Model = new BoxObstacle(
                obstacleID,
                transform.position.ToNumerics(),
                transform.localScale.ToNumerics()
            );
        }

        private void Update()
        {
            // Flag which is true when the gameobject is moved
            if (transform.hasChanged)
            {
                if (Model != null)
                {
                    Model.Center = transform.position.ToNumerics();
                    Model.Size = transform.localScale.ToNumerics();
                }

                if (transform.rotation != Quaternion.identity)
                {
                    transform.rotation = Quaternion.identity;
                    Debug.LogWarning($"[{gameObject.name}] Rotation is disallowed due to internal collision detection logic. Allign this object to the axes!");
                }

                transform.hasChanged = false;
            }
        }

        // Draws gizmos to visualize the obstacle in case there's no mesh (or it doesn't corespond to the mesh)
        private void OnDrawGizmos()
        {
            Gizmos.color = new Color(1f, 0f, 0f, 0.3f);
            Gizmos.DrawCube(transform.position, transform.localScale);
            Gizmos.color = Color.red;
            Gizmos.DrawWireCube(transform.position, transform.localScale);
        }
    }
}